openapi: 3.1.0
info:
  title: Physical AI Textbook API
  description: Backend API for the AI-Native Textbook Platform
  version: 1.0.0
  contact:
    name: Panaversity
servers:
  - url: http://localhost:8000
    description: Local development
  - url: https://physical-ai-api.onrender.com
    description: Production (Render)

paths:
  /health:
    get:
      summary: Health check
      operationId: healthCheck
      tags: [System]
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  timestamp:
                    type: string
                    format: date-time

  /api/auth/signup:
    post:
      summary: Register a new user
      operationId: signup
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/login:
    post:
      summary: Authenticate user
      operationId: login
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/logout:
    post:
      summary: End user session
      operationId: logout
      tags: [Authentication]
      security:
        - sessionToken: []
      responses:
        '200':
          description: Logged out successfully
        '401':
          description: Not authenticated

  /api/user/profile:
    get:
      summary: Get current user profile
      operationId: getProfile
      tags: [User]
      security:
        - sessionToken: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Not authenticated

    patch:
      summary: Update user profile
      operationId: updateProfile
      tags: [User]
      security:
        - sessionToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileUpdateRequest'
      responses:
        '200':
          description: Profile updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Not authenticated

  /api/chat:
    post:
      summary: Send a chat message to the Professor
      operationId: chat
      tags: [Chat]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Chat response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Chat service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/chat/history:
    get:
      summary: Get chat history for authenticated user
      operationId: getChatHistory
      tags: [Chat]
      security:
        - sessionToken: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Chat history
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/ChatHistoryItem'
                  total:
                    type: integer
        '401':
          description: Not authenticated

components:
  securitySchemes:
    sessionToken:
      type: apiKey
      in: cookie
      name: session_token

  schemas:
    SignupRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: student@example.com
        password:
          type: string
          minLength: 8
          example: securePassword123
        software_skills:
          type: array
          items:
            type: string
            enum: [Python, C++, JavaScript, None]
          default: []
          example: [Python]
        hardware_inventory:
          type: array
          items:
            type: string
            enum: [Arduino, Jetson, Raspberry Pi, None]
          default: []
          example: [Jetson]

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    AuthResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserProfile'
        session_expires_at:
          type: string
          format: date-time

    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        software_skills:
          type: array
          items:
            type: string
        hardware_inventory:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: date-time

    ProfileUpdateRequest:
      type: object
      properties:
        software_skills:
          type: array
          items:
            type: string
            enum: [Python, C++, JavaScript, None]
        hardware_inventory:
          type: array
          items:
            type: string
            enum: [Arduino, Jetson, Raspberry Pi, None]

    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          maxLength: 2000
          example: What is a ROS 2 Node?
        page_context:
          type: string
          description: Current page path for context-aware responses
          example: /docs/module-01-ros2/nodes
        user_profile:
          type: object
          description: Optional user profile for personalization (anonymous users)
          properties:
            software_skills:
              type: array
              items:
                type: string
            hardware_inventory:
              type: array
              items:
                type: string

    ChatResponse:
      type: object
      properties:
        answer:
          type: string
          description: The AI-generated response
        sources:
          type: array
          items:
            type: object
            properties:
              chunk_id:
                type: string
              source_page:
                type: string
              snippet:
                type: string
        personalized:
          type: boolean
          description: Whether the response was personalized to user profile

    ChatHistoryItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        message_text:
          type: string
        response_text:
          type: string
        page_context:
          type: string
        created_at:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        detail:
          type: string
        code:
          type: string
