import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Physical AI & Humanoid Robotics - Sidebar Configuration
 *
 * Two autogenerated sidebars for Module 1 (ROS 2) and Module 2 (Digital Twin)
 */
const sidebars: SidebarsConfig = {
  // Module 1: ROS 2 - The Robotic Nervous System
  module01Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'module-01-ros2',
    },
  ],

  // Module 2: Digital Twin
  module02Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'module-02-digital-twin',
    },
  ],
};

export default sidebars;
